[package]
name = "topcoat"
version = "0.1.0"
edition.workspace = true

[lib]
name = "topcoat"
path = "src/lib.rs"

[[bin]]
name = "topcoat"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
topcoat-db = { workspace = true }
topcoat-render = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
